import { Playfair_Display, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${playfair.variable} ${plusJakarta.variable} antialiased`}
      >
        <NavBar />
        <main className="relative isolate px-6 pt-14 lg:px-8 bg-background">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
